on:
  push:
    branches:
    - main
    - webapp
jobs:
  package-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: find * -type f -exec sha1sum {} \; > sha1.txt
      - uses: actions/upload-artifact@v4
        with:
          name: sha1
          path: sha1.txt
